services:
  backend:
    build:
      context: ./backend
    container_name: dinesmart-backend
    restart: on-failure
    ports:
      - "8000:8000"
    networks:
      - dinesmart-net

  frontend:
    build:
      context: ./frontend
    container_name: dinesmart-frontend
    restart: on-failure
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - dinesmart-net

networks:
  dinesmart-net:
