# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('menu', '0002_menuitemmodel_picture'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_name', models.CharField(blank=True, help_text='Custom name for the saved item', max_length=100, null=True)),
                ('custom_description', models.TextField(blank=True, help_text='Custom description for the saved item', null=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('is_display', models.BooleanField(default=False, help_text='Whether to display this item in the Home page')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuitemmodel')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saved_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Saved Item',
                'verbose_name_plural': 'Saved Items',
                'db_table': 'saved_item',
            },
        ),
        migrations.CreateModel(
            name='SavedItemIngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, help_text='Quantity of the ingredient used in the saved item')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredient.ingredientmodel')),
                ('saved_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_ingredients', to='saved_item.saveditemmodel')),
            ],
            options={
                'verbose_name': 'Saved Item Ingredient',
                'verbose_name_plural': 'Saved Item Ingredients',
                'db_table': 'saved_item_ingredient',
            },
        ),
    ]
