# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCartModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the Cart', max_digits=10, null=True)),
                ('order_type', models.CharField(blank=True, max_length=100, null=True)),
                ('menu_item_id', models.CharField(blank=True, help_text='Unique identifier for the menu item', max_length=100, null=True)),
                ('meals_from', models.CharField(blank=True, help_text="Source of the meal item (e.g., 'Saved Item', 'Menu')", max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, help_text='Name of the item', max_length=255, null=True)),
                ('custom_name', models.CharField(blank=True, help_text='Name of the item which set in saved_item', max_length=255, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the item', max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, help_text='Quantity of the item in the order', null=True)),
                ('picture', models.ImageField(blank=True, default='cart_images/default.jpg', help_text='Image of the menu item.', null=True, upload_to='cart_images/')),
                ('table_numbers', models.CharField(blank=True, help_text='Comma-separated table numbers (e.g., 1,3,4)', max_length=555, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the Cart is currently active')),
                ('deleted', models.BooleanField(default=False, help_text='Indicates if the Cart has been deleted')),
                ('meals', models.ForeignKey(blank=True, help_text='Reference to the meal item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='saved_item.saveditemmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Carts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
                'db_table': 'custom_cart',
            },
        ),
    ]
