# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_menuitemmodel_picture'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='requested', help_text='Status of the order (e.g., requested, cooking, be ready, deliveried cancelled)', max_length=20)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menuitemmodel')),
            ],
            options={
                'verbose_name': 'Admin Order',
                'verbose_name_plural': 'Admin Orders',
                'db_table': 'admin_order',
            },
        ),
        migrations.CreateModel(
            name='AdminOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.FloatField()),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ingredient.ingredientmodel')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='management.adminorder')),
            ],
            options={
                'verbose_name': 'Admin Order Item',
                'verbose_name_plural': 'Admin Order Items',
                'db_table': 'admin_order_item',
            },
        ),
    ]
