# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.CharField(max_length=100)),
                ('weight', models.PositiveSmallIntegerField(default=1)),
                ('calories', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('priority', models.BooleanField(default=True)),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, help_text='Price of the ingredient', max_digits=10)),
                ('picture', models.ImageField(blank=True, help_text='Image of the ingredient.', null=True, upload_to='ingredient_images/')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingredients',
                'db_table': 'ingredient',
            },
        ),
    ]
