# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0002_menuitemmodel_picture'),
        ('ingredient', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsedIngredientModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0, help_text='Quantity of the ingredient used in the saved item')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='ingredient.ingredientmodel')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='menu.menuitemmodel')),
            ],
            options={
                'verbose_name': 'Used Ingredient',
                'verbose_name_plural': 'Used Ingredients',
                'db_table': 'used_ingredient',
            },
        ),
    ]
