# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('address', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('saved_item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(blank=True, help_text='Unique identifier for the order', max_length=100, null=True, unique=True)),
                ('order_date', models.DateTimeField(auto_now_add=True, help_text='Date and time when the order was placed')),
                ('order_status', models.CharField(default='Pending', help_text='Status of the order (e.g., Pending, Completed, Cancelled)', max_length=50)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, help_text='Total amount for the order', max_digits=10, null=True)),
                ('address', models.CharField(blank=True, help_text='Delivery address for the order', max_length=255, null=True)),
                ('is_user_verified', models.BooleanField(default=False, help_text='Indicates if the user has verified their account')),
                ('is_address_verified', models.BooleanField(default=False, help_text='Indicates if the delivery address has been verified')),
                ('is_order_verified', models.BooleanField(default=False, help_text='Indicates if the order has been verified')),
                ('is_table_booked', models.BooleanField(default=False, help_text='Indicates if a table has been booked for the order')),
                ('is_take_away', models.BooleanField(default=False, help_text='Indicates if the order is for takeaway')),
                ('is_home_delivery', models.BooleanField(default=False, help_text='Indicates if the order is for home delivery')),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the order is currently active')),
                ('deleted', models.BooleanField(default=False, help_text='Indicates if the order has been deleted')),
                ('payment_status', models.CharField(default='Pending', help_text='Status of the payment (e.g., Pending, Completed, Failed)', max_length=50)),
                ('address_id', models.ForeignKey(blank=True, help_text='Reference to the delivery address', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'order',
            },
        ),
        migrations.CreateModel(
            name='OrderItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(blank=True, help_text='Type of order (e.g., Dine-in, Takeaway, Delivery)', max_length=50, null=True)),
                ('menu_item_id', models.CharField(blank=True, help_text='Unique identifier for the menu item', max_length=100, null=True)),
                ('meals_from', models.CharField(blank=True, help_text="Source of the meal item (e.g., 'Saved Item', 'Menu')", max_length=100, null=True)),
                ('item_name', models.CharField(blank=True, help_text='Name of the item', max_length=255, null=True)),
                ('item_price', models.DecimalField(blank=True, decimal_places=2, help_text='Price of the item', max_digits=10, null=True)),
                ('quantity', models.PositiveIntegerField(blank=True, default=1, help_text='Quantity of the item in the order', null=True)),
                ('item_description', models.TextField(blank=True, help_text='Description of the item', null=True)),
                ('item_image', models.URLField(blank=True, help_text="URL of the item's image", null=True)),
                ('table_numbers', models.CharField(blank=True, help_text='Comma-separated table numbers (e.g., 1,3,4)', max_length=555, null=True)),
                ('meals', models.ForeignKey(blank=True, help_text='Reference to the meal item', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='saved_item.saveditemmodel')),
                ('order', models.ForeignKey(help_text='Reference to the order', on_delete=django.db.models.deletion.CASCADE, related_name='items', to='order.ordermodel')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'db_table': 'order item',
            },
        ),
    ]
