# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TableModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(default=uuid.uuid4, max_length=64, unique=True)),
                ('table_number', models.PositiveIntegerField(unique=True)),
                ('total_seats', models.PositiveSmallIntegerField()),
                ('booked_seats', models.PositiveSmallIntegerField(default=0)),
                ('available_seats', models.PositiveSmallIntegerField(default=0)),
                ('table_status', models.CharField(choices=[('available', 'Available'), ('booked', 'Booked'), ('cleaning', 'Cleaning'), ('served', 'Served'), ('unavailable', 'Unavailable'), ('reserved', 'Reserved')], default='available', max_length=11)),
                ('condition_seats', models.PositiveSmallIntegerField(default=0, help_text='Minimum number of seats that can be accommodated at this table with at least minimum order.')),
                ('condition_order', models.PositiveSmallIntegerField(default=0.0, help_text='Minimum order amount for this table.')),
            ],
            options={
                'verbose_name': 'Table',
                'verbose_name_plural': 'Tables',
                'db_table': 'table',
            },
        ),
    ]
