# Generated by Django 4.2.23 on 2025-07-24 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItemModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price_type', models.CharField(choices=[('custom', 'Custom'), ('fixed', 'Fixed'), ('others', 'Others')], default='custom', max_length=10)),
                ('price', models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True)),
                ('thumbnail', models.URLField(blank=True, help_text='URL of the thumbnail image for the menu item.', null=True)),
                ('is_first_menu', models.BooleanField(default=False, help_text='Indicates if this is the first menu item in the list.')),
                ('is_special', models.BooleanField(default=False, help_text='Indicates if this menu item is a special item.')),
                ('is_table_menu', models.BooleanField(default=False, help_text='Indicates if this menu item is part of the table menu.')),
            ],
            options={
                'verbose_name': 'Menu Item',
                'verbose_name_plural': 'Menu Items',
                'db_table': 'menu_item',
            },
        ),
    ]
