# Generated by Django 4.2.26 on 2025-11-14 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitemmodel',
            name='picture',
            field=models.ImageField(blank=True, help_text='Image of the menu item.', null=True, upload_to='menu_item_images/'),
        ),
    ]
